Resources:
  HistoryTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tableHistory}
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  PlayerTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tablePlayer}
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
        - AttributeName: gameId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  FactionTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tableFaction}
      AttributeDefinitions:
        - AttributeName: factionId
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: factionId
          KeyType: HASH
        - AttributeName: gameId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  CommanderTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tableCommander}
      AttributeDefinitions:
        - AttributeName: commanderId
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: commanderId
          KeyType: HASH
        - AttributeName: gameId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  PlayerProfile:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.playerProfile}
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  FactionProfile:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.factionProfile}
      AttributeDefinitions:
        - AttributeName: factionId
          AttributeType: S
      KeySchema:
        - AttributeName: factionId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  CommanderProfile:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.commanderProfile}
      AttributeDefinitions:
        - AttributeName: commanderId
          AttributeType: S
        - AttributeName: factionId
          AttributeType: S
      KeySchema:
        - AttributeName: commanderId
          KeyType: HASH
        - AttributeName: factionId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  TournamentInfo:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tournamentInfo}
      AttributeDefinitions:
        - AttributeName: tournamentId
          AttributeType: S
      KeySchema:
        - AttributeName: tournamentId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  TournamentPlayers:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tournamentPlayers}
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
        - AttributeName: tournamentId
          AttributeType: S
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
        - AttributeName: tournamentId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  TournamentGames:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tournamentGames}
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
        - AttributeName: tournamentId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH
        - AttributeName: tournamentId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  HistoryTable:
    Value:
      Ref: HistoryTable
    Export:
      Name: ${self:custom.stage}-HistoryTableName
  PlayerProfileArn:
    Value:
      Fn::GetAtt:
        - HistoryTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtHistoryTableArn

  PlayerTable:
    Value:
      Ref: PlayerTable
    Export:
      Name: ${self:custom.stage}-PlayerTableName
  PlayerTableArn:
    Value:
      Fn::GetAtt:
        - PlayerTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtPlayerTableArn

  FactionTable:
    Value:
      Ref: FactionTable
    Export:
      Name: ${self:custom.stage}-FactionTableName
  FactionTableArn:
    Value:
      Fn::GetAtt:
        - FactionTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtFactionTableArn

  CommanderTable:
    Value:
      Ref: CommanderTable
    Export:
      Name: ${self:custom.stage}-CommanderTableName
  CommanderTableArn:
    Value:
      Fn::GetAtt:
        - CommanderTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtCommanderTableArn
      
  PlayerProfile:
    Value:
      Ref: PlayerProfile
    Export:
      Name: ${self:custom.stage}-PlayerProfileTableName
  PlayerProfileArn:
    Value:
      Fn::GetAtt:
        - PlayerProfile
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtPlayerProfileArn

